site_name: Naunet Astrochemistry Tool

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - mkdocstrings

nav:
  - Home: index.md
  - API References:
    - species: API/species.md
    - reaction: API/reaction.md
