[tool.poetry]
name = "naunet"
version = "0.1.0"
description = ""
authors = ["Chia-Jung Hsu <appolloford@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
sympy = "^1.7.1"
cleo = "^0.8.1"
Jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.0"
coverage = "^5.4"

[tool.poetry.scripts]
naunet = "naunet.console:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
