description = "Example: empty network"
files = ""
formats = ""
grain_model = ""
grain_symbol = "GRAIN"
surface_prefix = "#"
bulk_prefix = "@"
elements = []
pseudo_elements = []
allowed_species = []
extra_species = []
heating = []
cooling = []
shielding = {}
binding_energy = {}
photon_yield = {}
rate_modifier = {}
ode_modifier = {}
