description = "Example: empty network"
network = ""
format = ""
dustmodel = ""
dustspecies = []
elements = []
pseudo_elements = []
species = []
extra_species = []
heating = []
cooling = []
shielding = {}
binding_energy = {}
photon_yield = {}
rate_modifier = {}
ode_modifier = []
