description = "Example: a fake chemical network"
files = "minimal.kida"
formats = "kida"
grain_model = ""
grain_symbol = "GRAIN"
surface_prefix = "#"
bulk_prefix = "@"
elements = ["H", "C"]
pseudo_elements = []
allowed_species = ["H", "C2", "C", "CH"]
extra_species = []
heating = []
cooling = []
shielding = {}
binding_energy = {}
photon_yield = {}
rate_modifier = {}
ode_modifier = {}
