description = "Example: a fake chemical network"
network = "minimal.kida"
format = "kida"
grain_model = ""
elements = ["H", "C"]
pseudo_elements = []
species = ["H", "C2", "C", "CH"]
extra_species = []
heating = []
cooling = []
shielding = {}
binding_energy = {}
photon_yield = {}
rate_modifier = {}
ode_modifier = {}
