description = "Example: a fake chemical network"
network = "fake.krome"
format = "krome"
dustmodel = "none"
dustspecies = []
elements = ["H", "D"]
pseudo_elements = []
species = ["H", "D", "H2", "HD"]
extra_species = []
heating = []
cooling = []
shielding = {}
binding_energy = {}
photon_yield = {}
rate_modifier = {}
ode_modifier = []
