# test on MacOS
name: macos

on:
  push:
    branches: [ main, thermal ]
    paths-ignore:
      - 'docs/**'
      - 'notebooks/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'notebooks/**'

jobs:

  install:
    strategy:
      matrix:
        os: [macos-latest]
        python: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Pyhon
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: Gr1N/setup-poetry@v4

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ matrix.os }}-python${{ matrix.python }}-poetry-${{ hashFiles('poetry.lock') }}

      - run: poetry --version

      - name: Install package dependencies
        run: poetry install

      - name: Pytest
        run: poetry run pytest -rs -o log_cli=true -o log_cli_level=DEBUG --runslow test

      # ? It seems poetry install doesn't install package to the system
      - name: Install package
        run: pip install .

      - name: Check package installed
        run: naunet --version
        
  build:
    needs: install
    
    runs-on: macos-latest
    
    strategy:
      fail-fast: false

    env:
      build_dir: "build"
      config: "Release"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ hashFiles('poetry.lock') }}

      - name: Install package
        run: pip install .

      - name: Install packages for testing
        run: pip install numpy

      - name: Create naunet examples
        run: source ./scripts/actions/create_examples.sh

      - name: Install BLAS & LAPACK
        run: brew install openblas lapack
          
      - name: Install boost
        # boost 1.76 us "mp" as a namspace and conflict with the proton mass constant
        # download boost 1.75 instead
        # run: brew install boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
          tar -zxf boost_1_75_0.tar.gz && cd boost_1_75_0
          ./bootstrap.sh
          sudo ./b2 install

      - name: Install SuiteSparse
        run: brew install suite-sparse

      - name: Install SUNDIALS
        run: brew install sundials

      - name: Build naunet examples
        run: source ./scripts/actions/build_examples.sh

      - name: Test naunet examples
        run: source ./scripts/actions/test_examples.sh
