# test on Ubuntu
name: ubuntu

on:
  push:
    branches: [ main, clangformat ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:

  install:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        python: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Pyhon
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: Gr1N/setup-poetry@v4

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ matrix.os }}-python${{ matrix.python }}-poetry-${{ hashFiles('poetry.lock') }}

      - run: poetry --version

      - name: Install package dependencies
        run: poetry install

      - name: Pytest
        run: poetry run pytest -rs -o log_cli=true -o log_cli_level=DEBUG --runslow test

      # ? It seems poetry install doesn't install package to the system
      - name: Install package
        run: pip install .

      - name: Check package installed
        run: naunet --version
        
  build:
    needs: install
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            cuda: "11.0"
            python: "3.8"

          - os: ubuntu-18.04
            cuda: "10.2"
            python: "3.8"

    env:
      build_dir: "build"
      config: "Release"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ hashFiles('poetry.lock') }}

      - name: Install package
        run: pip install .

      - name: Install packages for testing
        run: pip install numpy

      - name: Create naunet examples
        run: source ./scripts/actions/create_examples.sh

      - name: Install BLAS & LAPACK
        run: sudo apt-get install libblas-dev liblapack-dev

      - name: Cache boost
        uses: actions/cache@v2
        id: boost
        with:
          path: ~/boost
          key: ${{ matrix.os }}-boost1.65
          
      - name: Install boost
        env:
          CACHE_HIT: ${{ steps.boost.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/boost/* /
          else
            sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
            mkdir -p ~/boost
            for dep in libboost1.65-dev; do
                dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
            done
          fi
          
      - name: Install SuiteSparse dependencies
        run: sudo apt-get install libgmp3-dev libmpc-dev

      - name: Cache SuiteSparse
        uses: actions/cache@v2
        id: suitesparse
        with:
          path: ~/suitesparse
          key: ${{ matrix.os }}-suitesparse

      - name: Install SuiteSparse
        env:
          CACHE_HIT: ${{ steps.suitesparse.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/suitesparse /usr/local/suitesparse
          else
            source ./scripts/actions/install_suitesparse.sh
          fi

      # Use the script from https://github.com/ptheywood/cuda-cmake-github-actions
      - name: Install CUDA
        env:
          cuda: ${{ matrix.cuda }}
        run: |
          source ./scripts/actions/install_cuda_ubuntu.sh
          if [[ $? -eq 0 ]]; then
            # Set paths for subsequent steps, using ${CUDA_PATH}
            echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
            echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
            echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
            echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Cache SUNDIALS
        uses: actions/cache@v2
        id: sundials
        with:
          path: ~/sundials
          key: ${{ matrix.os }}-sundials

      - name: Install SUNDIALS
        env:
          CACHE_HIT: ${{ steps.sundials.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/sundials /usr/local/sundials
          else
            source ./scripts/actions/install_sundials.sh
          fi

      - name: Build naunet examples
        run: source ./scripts/actions/build_examples.sh

      - name: Test naunet examples
        run: source ./scripts/actions/test_examples.sh
